browser=chrome
docuportBETA=https://beta.docuport.app/
google.url=https://www.google.com
guru.url=https://demo.guru99.com/test/upload
loop.practice=https://loopcamp.vercel.app/
dynamicLoading.username=tomsmith
dynamicLoading.incorrectPassword=incorrect